server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SecurityMySQL?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: dipak
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      for creating table before inserting value
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

